#!/bin/bash

# Script used to generate 5000 random graphs
# using the code generated by graph_gen.cpp
# In this sample, all generated graphs have
# 10 vertices.

n=0
while [ $n -lt 5000 ]; do
  ./a.out 10 $n
  n=`expr $n + 1`
done
